browser=chrome
url=https://hrm.neotechacademy.com
username=admin
password=Neotech@123

dbUrl = jdbc:mysql://hrm.neotechacademy.com:3306/classicmodels
dbUsername = user1
dbPassword = Neotech@123

ApiUsername=tester
ApiPassword=Student@Neo